# Generated by Django 3.2 on 2022-02-24 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='add_remark',
        ),
    ]
